# Site Settings
title: Liangliang Zhang's HomepageðŸ¡
email: zhangl41@rpi.edu
description: >
  Liangliang's Personal Website.
baseurl:
url: "http://liangliang6v6.github.io"
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ðŸª„ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)
# repo color theme
repo_theme_light: default       # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark           # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat    # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed  # https://github.com/ryo-ma/github-profile-trophy
rss_icon: true
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM